# Generated by Django 3.0.3 on 2020-06-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='gold'),
        ),
    ]
