# Generated by Django 3.0.3 on 2020-05-31 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
